function S = calcS(P00,P01,P10,P11,velObsVar)
%CALCS
%    S = CALCS(P00,P01,P10,P11,VELOBSVAR)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    22-Nov-2019 22:24:30

S = reshape([P00+velObsVar,P10,P01,P11+velObsVar],[2, 2]);
