function F = calcFmat(dvx,dvy,psi)
%CALCFMAT
%    F = CALCFMAT(DVX,DVY,PSI)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    19-Sep-2017 19:37:55

t2 = cos(psi);
t3 = sin(psi);
F = reshape([1.0,0.0,0.0,0.0,1.0,0.0,-dvx.*t3-dvy.*t2,dvx.*t2-dvy.*t3,1.0],[3, 3]);
