function Pnext = calcPmat(P00,P01,P02,P10,P11,P12,P20,P21,P22,dazVar,dvx,dvy,dvxVar,dvyVar,psi)
%CALCPMAT
%    PNEXT = CALCPMAT(P00,P01,P02,P10,P11,P12,P20,P21,P22,DAZVAR,DVX,DVY,DVXVAR,DVYVAR,PSI)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    05-Nov-2019 10:12:39

t2 = sin(psi);
t3 = cos(psi);
t4 = dvy.*t3;
t5 = dvx.*t2;
t6 = t4+t5;
t8 = P22.*t6;
t7 = P02-t8;
t9 = dvx.*t3;
t11 = dvy.*t2;
t10 = t9-t11;
t12 = dvxVar.*t2.*t3;
t13 = t2.^2;
t14 = t3.^2;
t15 = P22.*t10;
t16 = P12+t15;
Pnext = reshape([P00-P20.*t6+dvxVar.*t14+dvyVar.*t13-t6.*t7,P10+t12+P20.*t10-t6.*t16-dvyVar.*t2.*t3,P20-t8,P01+t12-P21.*t6+t7.*t10-dvyVar.*t2.*t3,P11+P21.*t10+dvxVar.*t13+dvyVar.*t14+t10.*t16,P21+t15,t7,t16,P22+dazVar],[3, 3]);
