function Pnext = calcPmat(P00,P01,P02,P10,P11,P12,P20,P21,P22,dazVar,dvx,dvy,dvxVar,dvyVar,psi)
%CALCPMAT
%    PNEXT = CALCPMAT(P00,P01,P02,P10,P11,P12,P20,P21,P22,DAZVAR,DVX,DVY,DVXVAR,DVYVAR,PSI)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    22-Nov-2019 22:24:29

t2 = sin(psi);
t3 = cos(psi);
t4 = dvxVar.*t2.*t3;
t5 = t2.^2;
t6 = t3.^2;
t7 = dvy.*t3;
t8 = dvx.*t2;
t9 = t7+t8;
t10 = dvx.*t3;
t12 = dvy.*t2;
t11 = t10-t12;
t13 = P11.*t11;
t14 = P10.*t11;
t15 = P20+t14-P00.*t9;
t16 = P21+t13-P01.*t9;
Pnext = reshape([P00+dvxVar.*t6+dvyVar.*t5,P10+t4-dvyVar.*t2.*t3,t15,P01+t4-dvyVar.*t2.*t3,P11+dvxVar.*t5+dvyVar.*t6,t16,P02-P00.*t9+P01.*t11,P12+t13-P10.*t9,P22+dazVar-P02.*t9+P12.*t11-t9.*t15+t11.*t16],[3, 3]);
