function K = calcK(P00,P01,P10,P11,P20,P21,velObsVar)
%CALCK
%    K = CALCK(P00,P01,P10,P11,P20,P21,VELOBSVAR)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    22-Nov-2019 22:24:30

t2 = P00.*velObsVar;
t3 = P11.*velObsVar;
t4 = velObsVar.^2;
t5 = P00.*P11;
t8 = P01.*P10;
t6 = t2+t3+t4+t5-t8;
t7 = 1.0./t6;
t9 = P11+velObsVar;
t10 = P00+velObsVar;
K = reshape([-P01.*P10.*t7+P00.*t7.*t9,-P10.*P11.*t7+P10.*t7.*t9,-P10.*P21.*t7+P20.*t7.*t9,-P00.*P01.*t7+P01.*t7.*t10,-P01.*P10.*t7+P11.*t7.*t10,-P01.*P20.*t7+P21.*t7.*t10],[3, 2]);
